package com.welove520.timelineupload.task;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.welove520.timelineupload.task.TimelineTask;

import com.welove520.timelineupload.task.TimelineTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timelineTaskDaoConfig;

    private final TimelineTaskDao timelineTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timelineTaskDaoConfig = daoConfigMap.get(TimelineTaskDao.class).clone();
        timelineTaskDaoConfig.initIdentityScope(type);

        timelineTaskDao = new TimelineTaskDao(timelineTaskDaoConfig, this);

        registerDao(TimelineTask.class, timelineTaskDao);
    }
    
    public void clear() {
        timelineTaskDaoConfig.clearIdentityScope();
    }

    public TimelineTaskDao getTimelineTaskDao() {
        return timelineTaskDao;
    }

}
