package com.welove520.timelineupload.task;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.welove520.timelineupload.task.Photo;
import com.welove520.timelineupload.task.TimelineTask;

import com.welove520.timelineupload.task.PhotoDao;
import com.welove520.timelineupload.task.TimelineTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoDaoConfig;
    private final DaoConfig timelineTaskDaoConfig;

    private final PhotoDao photoDao;
    private final TimelineTaskDao timelineTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        timelineTaskDaoConfig = daoConfigMap.get(TimelineTaskDao.class).clone();
        timelineTaskDaoConfig.initIdentityScope(type);

        photoDao = new PhotoDao(photoDaoConfig, this);
        timelineTaskDao = new TimelineTaskDao(timelineTaskDaoConfig, this);

        registerDao(Photo.class, photoDao);
        registerDao(TimelineTask.class, timelineTaskDao);
    }
    
    public void clear() {
        photoDaoConfig.clearIdentityScope();
        timelineTaskDaoConfig.clearIdentityScope();
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

    public TimelineTaskDao getTimelineTaskDao() {
        return timelineTaskDao;
    }

}
