package com.welove520.timelineupload.task;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIMELINE_TASK".
*/
public class TimelineTaskDao extends AbstractDao<TimelineTask, Long> {

    public static final String TABLENAME = "TIMELINE_TASK";

    /**
     * Properties of entity TimelineTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property SendTimeMS = new Property(2, Long.class, "sendTimeMS", false, "SEND_TIME_MS");
        public final static Property Progress = new Property(3, Integer.class, "progress", false, "PROGRESS");
        public final static Property UploadStatus = new Property(4, Integer.class, "uploadStatus", false, "UPLOAD_STATUS");
        public final static Property Uploaded = new Property(5, boolean.class, "uploaded", false, "UPLOADED");
    }

    private DaoSession daoSession;


    public TimelineTaskDao(DaoConfig config) {
        super(config);
    }
    
    public TimelineTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TIMELINE_TASK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"SEND_TIME_MS\" INTEGER," + // 2: sendTimeMS
                "\"PROGRESS\" INTEGER," + // 3: progress
                "\"UPLOAD_STATUS\" INTEGER," + // 4: uploadStatus
                "\"UPLOADED\" INTEGER NOT NULL );"); // 5: uploaded
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_TIMELINE_TASK_SEND_TIME_MS_DESC ON \"TIMELINE_TASK\"" +
                " (\"SEND_TIME_MS\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TIMELINE_TASK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TimelineTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Long sendTimeMS = entity.getSendTimeMS();
        if (sendTimeMS != null) {
            stmt.bindLong(3, sendTimeMS);
        }
 
        Integer progress = entity.getProgress();
        if (progress != null) {
            stmt.bindLong(4, progress);
        }
 
        Integer uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindLong(5, uploadStatus);
        }
        stmt.bindLong(6, entity.getUploaded() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TimelineTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Long sendTimeMS = entity.getSendTimeMS();
        if (sendTimeMS != null) {
            stmt.bindLong(3, sendTimeMS);
        }
 
        Integer progress = entity.getProgress();
        if (progress != null) {
            stmt.bindLong(4, progress);
        }
 
        Integer uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindLong(5, uploadStatus);
        }
        stmt.bindLong(6, entity.getUploaded() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(TimelineTask entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TimelineTask readEntity(Cursor cursor, int offset) {
        TimelineTask entity = new TimelineTask( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // sendTimeMS
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // progress
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // uploadStatus
            cursor.getShort(offset + 5) != 0 // uploaded
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TimelineTask entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSendTimeMS(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setProgress(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setUploadStatus(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setUploaded(cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TimelineTask entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TimelineTask entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TimelineTask entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
